package in.kanchuk.sms.template;

public enum OrderNotificationType {
    ORDER_CONFIRMED,
    PAYMENT_CONFIRMED,
    ORDER_PACKED,
    ORDER_SHIPPED,
    OUT_FOR_DELIVERY,
    ORDER_DELIVERED,
    ORDER_CANCELLED,
    RETURN_INITIATED,
    RETURN_APPROVED,
    RETURN_REJECTED,
    REFUND_COMPLETED
}
