ALTER TABLE products
  ADD COLUMN IF NOT EXISTS brand           VARCHAR(150),
  ADD COLUMN IF NOT EXISTS slug            VARCHAR(255) UNIQUE,
  ADD COLUMN IF NOT EXISTS supplier_sku    VARCHAR(100),
  ADD COLUMN IF NOT EXISTS swatch_available BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS swatch_price    NUMERIC(10,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS color_families  JSONB,
  ADD COLUMN IF NOT EXISTS attributes      JSONB,
  ADD COLUMN IF NOT EXISTS rating          NUMERIC(3,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS review_count    INT NOT NULL DEFAULT 0;
